### ISSUE TITLE
Error appear when starting run

### ISSUE THREAD

**Issue by garethng** [liuweiGL/vite-plugin-mkcert#46]
### Describe the bug

Error appear when starting run

### System Info

Output of `npx envinfo --system --npmPackages vite,@vitejs/plugin-vue --binaries --browsers`:

```node
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 33.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.1.0 
    vite: ^3.1.3 => 3.1.3 
```

Used package manager: 
pnpm

### Logs 

```node
failed to load config from /Users/garethng/Documents/code/HotelManagementWebsite/vite.config.ts
error when starting dev server:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at new NodeError (node:internal/errors:393:5)
    at fileURLToPath (node:internal/url:1486:11)
    at node_modules/.pnpm/vite@3.0.0/node_modules/vite/dist/node/constants.js (/Users/garethng/Documents/code/HotelManagementWebsite/node_modules/.pnpm/vite-plugin-mkcert@1.8.0_vite@3.1.3/node_modules/vite-plugin-mkcert/dist/mkcert.js:3544:88)
    at __init (/Users/garethng/Documents/code/HotelManagementWebsite/node_modules/.pnpm/vite-plugin-mkcert@1.8.0_vite@3.1.3/node_modules/vite-plugin-mkcert/dist/mkcert.js:10:56)
    at node_modules/.pnpm/vite@3.0.0/node_modules/vite/dist/node/chunks/dep-561c5231.js (/Users/garethng/Documents/code/HotelManagementWebsite/node_modules/.pnpm/vite-plugin-mkcert@1.8.0_vite@3.1.3/node_modules/vite-plugin-mkcert/dist/mkcert.js:71746:5)
    at __init (/Users/garethng/Documents/code/HotelManagementWebsite/node_modules/.pnpm/vite-plugin-mkcert@1.8.0_vite@3.1.3/node_modules/vite-plugin-mkcert/dist/mkcert.js:10:56)
    at Object.<anonymous> (/Users/garethng/Documents/code/HotelManagementWebsite/node_modules/.pnpm/vite-plugin-mkcert@1.8.0_vite@3.1.3/node_modules/vite-plugin-mkcert/dist/mkcert.js:94778:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at _require.extensions.<computed> [as .js] (file:///Users/garethng/Documents/code/HotelManagementWebsite/node_modules/.pnpm/vite@3.1.3_less@4.1.3+terser@5.15.0/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63516:17)
 ELIFECYCLE  Command failed with exit code 1.
```

---

**Comment by liuweiGL** [comment]
#47
