### ISSUE TITLE
Windows环境，node16.10.0，安装后运行项目直接报错

### ISSUE THREAD

**Issue by SKT1yang** [liuweiGL/vite-plugin-mkcert#50]
一个vue项目，run dev时报了mkcert.js里path路径传参undefined的问题，我单独起个纯粹的vite项目是没问题的
报错信息如下：

failed to load config from C:\Users\92597\Desktop\新建文件夹\csmp-issap\csmp-issap\vue\issap\vite.config.ts
error when starting dev server:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. **Received undefined**
    at new NodeError (node:internal/errors:371:5)
    at fileURLToPath (node:internal/url:1417:11)
    at node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/constants.js (C:\Users\92597\Desktop\新建文件夹\csmp-issap\csmp-issap\vue\issap\node_modules\.pnpm\vite-plugin-mkcert@1.10.0_vite@3.1.3\node_modules\vite-plugin-**mkcert\dist\mkcert.js**:3581:41)
    at __init (C:\Users\92597\Desktop\新建文件夹\csmp-issap\csmp-issap\vue\issap\node_modules\.pnpm\vite-plugin-mkcert@1.10.0_vite@3.1.3\node_modules\vite-plugin-mkcert\dist\mkcert.js:10:56)
    at node_modules/.pnpm/vite@3.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js (C:\Users\92597\Desktop\新建文件夹\csmp-issap\csmp-issap\vue\issap\node_modules\.pnpm\vite-plugin-mkcert@1.10.0_vite@3.1.3\node_modules\vite-plugin-mkcert\dist\mkcert.js:72994:5)
    at __init (C:\Users\92597\Desktop\新建文件夹\csmp-issap\csmp-issap\vue\issap\node_modules\.pnpm\vite-plugin-mkcert@1.10.0_vite@3.1.3\node_modules\vite-plugin-mkcert\dist\mkcert.js:10:56)
    at Object.<anonymous> (C:\Users\92597\Desktop\新建文件夹\csmp-issap\csmp-issap\vue\issap\node_modules\.pnpm\vite-plugin-mkcert@1.10.0_vite@3.1.3\node_modules\vite-plugin-mkcert\dist\mkcert.js:96514:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object._require.extensions.<computed> [as .js] (file:///C:/Users/92597/Desktop/%E6%96%B0%E5%BB%BA%E6%96%87%E4%BB%B6%E5%A4%B9/csmp-issap/csmp-issap/vue/issap/node_modules/.pnpm/vite@3.1.3_less@4.1.3/node_modules/vite/dist/node/chunks/dep-557f29e6.js:63516:17)
 ELIFECYCLE  Command failed with exit code 1.

Used package manager: pnpm

node: 16.10.0

**Comment by liuweiGL** [comment]
升级最新版本
