### ISSUE TITLE
commandResult.toString(...).replaceAll is not a function

### ISSUE THREAD

**Issue by u373693041** [liuweiGL/vite-plugin-mkcert#60]
system: win11
use vite-plugin-mkcert ^1.13.0 get error
1.10.1 work well
```
error when starting dev server:
TypeError: commandResult.toString(...).replaceAll is not a function
    at Mkcert.retainExistedCA (d:\apps\docker-lnmp\www\trunk\static\static-src\static-advanceV2\node_modules\vite-plugin-mkcert\dist\mkcert.js:514:32)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Mkcert.createCertificate (d:\apps\docker-lnmp\www\trunk\static\static-src\static-advanceV2\node_modules\vite-plugin-mkcert\dist\mkcert.js:542:5)
    at async Mkcert.regenerate (d:\apps\docker-lnmp\www\trunk\static\static-src\static-advanceV2\node_modules\vite-plugin-mkcert\dist\mkcert.js:566:5)
    at async Mkcert.renew (d:\apps\docker-lnmp\www\trunk\static\static-src\static-advanceV2\node_modules\vite-plugin-mkcert\dist\mkcert.js:665:7)
    at async Mkcert.install (d:\apps\docker-lnmp\www\trunk\static\static-src\static-advanceV2\node_modules\vite-plugin-mkcert\dist\mkcert.js:678:7)
    at async config (d:\apps\docker-lnmp\www\trunk\static\static-src\static-advanceV2\node_modules\vite-plugin-mkcert\dist\mkcert.js:708:27)
    at async runConfigHook (file:///d:/apps/docker-lnmp/www/trunk/static/static-src/static-advanceV2/node_modules/vite/dist/node/chunks/dep-3007b26d.js:62340:25)
    at async resolveConfig (file:///d:/apps/docker-lnmp/www/trunk/static/static-src/static-advanceV2/node_modules/vite/dist/node/chunks/dep-3007b26d.js:61841:14)
    at async createServer (file:///d:/apps/docker-lnmp/www/trunk/static/static-src/static-advanceV2/node_modules/vite/dist/node/chunks/dep-3007b26d.js:61127:20)
```

**Comment by u373693041** [comment]
> The lastest plugin requires nodejs >= v16.7.0
> 
> https://github.com/liuweiGL/vite-plugin-mkcert/blob/20cce3a7937d17762cf8003105beee5e84c8cc4d/package.json#L21-L23

Thank you, but Vite supports 14.18+, so I hope that this plugin also support 14.18+
