### ISSUE TITLE
error when starting dev server: Error: connect ETIMEDOUT 20.205.243.166:443     at Function.AxiosError.from (file:///D:/cx/chenxi-big-screen/node_modules/axios/lib/core/AxiosError.js:89:14)     at RedirectableRequest.handleRequestError (file:///D:/cx/chenxi-big-screen/node_modules/axios/lib/adapters/http.js:593:25)     at RedirectableRequest.emit (events.js:400:28)     at ClientRequest.eventHandlers.<computed> (D:\cx\chenxi-big-screen\node_modules\follow-redirects\index.js:14:24)     at ClientRequest.emit (events.js:400:28)     at TLSSocket.socketErrorListener (_http_client.js:475:9)     at TLSSocket.emit (events.js:400:28)     at emitErrorNT (internal/streams/destroy.js:106:8)     at emitErrorCloseNT (internal/streams/destroy.js:74:3)     at processTicksAndRejections (internal/process/task_queues.js:82:21)

### ISSUE THREAD

**Issue by hufei1** [liuweiGL/vite-plugin-mkcert#73]
### System Info

Output of `npx envinfo --system --npmPackages vite,vite-plugin-mkcert --binaries --browsers`:

```node

```

Used package manager: 

### Logs 

```node

```

---

**Comment by hufei1** [comment]
error when starting dev server:
Error: connect ETIMEDOUT 20.205.243.166:443
    at Function.AxiosError.from (file:///D:/cx/chenxi-big-screen/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///D:/cx/chenxi-big-screen/node_modules/axios/lib/adapters/http.js:593:25)
    at RedirectableRequest.emit (events.js:400:28)
    at ClientRequest.eventHandlers.<computed> (D:\cx\chenxi-big-screen\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by liuweiGL** [comment]
https://github.com/liuweiGL/vite-plugin-mkcert/blob/main/README-zh_CN.md#source
