### ISSUE TITLE
Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded

### ISSUE THREAD

**Issue by magic3584** [liuweiGL/vite-plugin-mkcert#77]
### Describe the bug

Error when starting dev server: `pnpm vite`

### Reproduction

    "vite-plugin-mkcert": "^1.17.1",

### System Info

Output of `npx envinfo --system --npmPackages vite,vite-plugin-mkcert --binaries --browsers`:

```node
System:
    OS: macOS 13.5
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
    pnpm: 7.14.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.62
    Safari: 16.6
```

Used package manager: 
pnpm

### Logs 

```node
 ERROR  error when starting dev server:                               13:24:53
Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
    at AxiosError.from (/node_modules/.pnpm/axios@1.6.2_debug@4.3.4/node_modules/axios/dist/node/axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (/node_modules/.pnpm/axios@1.6.2_debug@4.3.4/node_modules/axios/dist/node/axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest._processResponse (/node_modules/.pnpm/follow-redirects@1.15.3_debug@4.3.4/node_modules/follow-redirects/index.js:383:10)
    at RedirectableRequest._onNativeResponse (/node_modules/.pnpm/follow-redirects@1.15.3_debug@4.3.4/node_modules/follow-redirects/index.js:65:10)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

---

**Comment by magic3584** [comment]
Why this issue is closed without any explanation?
